version: "3"

vars:
  BIN: uagplugin
  BUILD_DIR: bin
  PKG: ./...

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  tidy:
    desc: Sync go.mod and go.sum
    cmds:
      - go mod tidy

  fmt:
    desc: Format code
    cmds:
      - go fmt {{.PKG}}

  vet:
    desc: Run go vet
    deps: [fmt]
    cmds:
      - go vet {{.PKG}}

  lint:
    desc: Run linters (golangci-lint if available; falls back to go vet)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run ./...
        else
          echo "golangci-lint not found; running go vet instead"
          go vet {{.PKG}}
        fi

  build:
    desc: Build the binary into {{.BUILD_DIR}}/{{.BIN}}
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BIN}} .
    sources:
      - "**/*.go"
    generates:
      - "{{.BUILD_DIR}}/{{.BIN}}"

  run:
    desc: Run the app directly (passes CLI args)
    env:
      UAG_ENV: development
    cmds:
      - go run . {{.CLI_ARGS}}

  install:
    desc: "Install example plugin"
    env:
      UAG_ENV: development
    cmds:
      - go run . install --dir ./examples/uag-fileplugin
      - go run . install --dir ./examples/uag-apiplugin

  exec:
    desc: Run the built binary (builds first)
    deps: [build]
    cmds:
      - ./{{.BUILD_DIR}}/{{.BIN}} {{.CLI_ARGS}}

  test:
    desc: Run unit tests with race detector and coverage
    cmds:
      - go test -race -coverprofile=coverage.out {{.PKG}}
      - go tool cover -func=coverage.out | tail -n 1 || true
    sources:
      - "**/*.go"
    generates:
      - coverage.out

  clean:
    desc: Remove build artifacts and clean test cache
    cmds:
      - rm -rf {{.BUILD_DIR}} coverage.out
      - go clean -testcache

  watch:
    desc: Rebuild and run on changes (requires reflex)
    cmds:
      - |
        if command -v reflex >/dev/null 2>&1; then
          reflex -r '\.go$' -- sh -c 'task exec'
        else
          echo "Install reflex: go install github.com/cespare/reflex@latest"
          exit 1
        fi

  release:
    desc: Build a static Linux amd64 release binary with embedded version info (uses latest tag by default)
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - |
        VERSION="${VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)}"; \
        COMMIT="$(git rev-parse --short HEAD)"; \
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; \
        LDFLAGS="-s -w -X github.com/nikhiljohn10/uagplugin/internal/version.Version=${VERSION} -X github.com/nikhiljohn10/uagplugin/internal/version.Commit=${COMMIT} -X github.com/nikhiljohn10/uagplugin/internal/version.Date=${DATE}"; \
        echo "Building ${VERSION} (${COMMIT}) ${DATE} for linux/amd64"; \
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "$LDFLAGS" -o {{.BUILD_DIR}}/{{.BIN}}-linux-amd64 .; \
        (command -v sha256sum >/dev/null 2>&1 && sha256sum {{.BUILD_DIR}}/{{.BIN}}-linux-amd64 > {{.BUILD_DIR}}/{{.BIN}}-linux-amd64.sha256) || true

  release-local:
    desc: Build a release binary for the current platform with embedded version info
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - |
        VERSION="${VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)}"; \
        COMMIT="$(git rev-parse --short HEAD)"; \
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; \
        LDFLAGS="-s -w -X github.com/nikhiljohn10/uagplugin/internal/version.Version=${VERSION} -X github.com/nikhiljohn10/uagplugin/internal/version.Commit=${COMMIT} -X github.com/nikhiljohn10/uagplugin/internal/version.Date=${DATE}"; \
        echo "Building ${VERSION} (${COMMIT}) ${DATE} for $(go env GOOS)/$(go env GOARCH)"; \
        go build -trimpath -ldflags "$LDFLAGS" -o {{.BUILD_DIR}}/{{.BIN}} .; \
        ./{{.BUILD_DIR}}/{{.BIN}} version

  show-version:
    desc: Preview version output using ldflags from git tag/commit/date (no artifact kept)
    silent: true
    cmds:
      - |
        VERSION="${VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)}"; \
        COMMIT="$(git rev-parse --short HEAD)"; \
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; \
        LDFLAGS="-X github.com/nikhiljohn10/uagplugin/internal/version.Version=${VERSION} -X github.com/nikhiljohn10/uagplugin/internal/version.Commit=${COMMIT} -X github.com/nikhiljohn10/uagplugin/internal/version.Date=${DATE}"; \
        go build -trimpath -ldflags "$LDFLAGS" -o /tmp/{{.BIN}} . && /tmp/{{.BIN}} version

  tag:
    desc: "Create and push an annotated git tag (usage: task tag -- VERSION=vX.Y.Z)"
    cmds:
      - test -n "{{.VERSION}}" || (echo "Set VERSION=vX.Y.Z via 'task tag -- VERSION=vX.Y.Z'" && exit 1)
      - git commit -a -m "bump to version {{.VERSION}}" || (echo "No changes to commit" && exit 0)
      - git tag -a {{.VERSION}} -m "Release {{.VERSION}}"
      - git push origin
      - git push origin {{.VERSION}}

  prepare:
    desc: Pre-flight checks before tagging (clean tree, verify, and show computed version)
    cmds:
      # - git diff --quiet HEAD || (echo "Working tree not clean. Commit or stash changes before releasing." && exit 1)
      - task: verify
      - task: show-version

  verify:
    desc: Quick checks (tidy, fmt, vet, test)
    deps: [tidy, fmt, vet, test]
